server:
  port: 9000
  servlet.context-path: /api

spring.application.name: consumer-blue

info:
  app:
    name: Consumer Blue
    protocol: http
    description: 'This is the Pact workshop demo'
  version: 1.0.0
  contact:
    author: Waterstrong
    email: shuiqianglin@gmail.com

decision:
  api:
    name: Decision Service
    baseUrl: http://localhost:8081/api
    username: username
    password: '******'
    poolSize: 20
    timeout: 5000

address:
  api:
    name: Address Service
    baseUrl: http://localhost:8082/api
    username: username
    password: '******'
    poolSize: 20
    timeout: 5000